#! /bin/bash

if test -z "$1"
then
    echo "No directory was given"
else
    if test -d "$1"
    then
	cd "$1"
	cd ..
	R CMD build "$1"
	R CMD check "$1"*.tar.gz #> "$1".Rreport
#	open "$1".Rreport
    else
	echo "No such directory"
    fi
fi
